export type GetGithubDataResponse = {
    id: number,
    node_id: string,
    name: string,
    full_name: string,
    private: boolean,
    owner: Owner,
    html_url: string | URL,
    description: string,
    fork: boolean,
    url: string | URL,
    forks_url: string | URL,
    keys_url: string | URL,
    collaborators_url: string | URL,
    teams_url: string | URL,
    hooks_url: string | URL,
    issue_events_url: string | URL,
    events_url: string | URL,
    assignees_url: string | URL
    branches_url: string | URL,
    tags_url: string | URL,
    blobs_url: string | URL,
    git_tags_url: string | URL
    git_refs_url: string | URL,
    trees_url: string | URL,
    statuses_url: string | URL,
    languages_url: string | URL,
    stargazers_url: string | URL,
    contributors_url: string | URL,
    subscribers_url: string | URL,
    subscription_url:string | URL,
    commits_url: string | URL,
    git_commits_url: string | URL,
    comments_url: string | URL,
    issue_comment_url: string | URL,
    contents_url: string | URL,
    compare_url: string | URL,
    merges_url: string | URL,
    archive_url: string | URL,
    downloads_url: string | URL,
    issues_url: string | URL,
    pulls_url: string | URL,
    milestones_url: string | URL,
    notifications_url: string | URL,
    labels_url: string | URL,
    releases_url: string | URL,
    deployments_url: string | URL,
    created_at: string | Date,
    updated_at: string | Date,
    pushed_at: string | Date,
    git_url: string | URL,
    ssh_url: string | URL,
    clone_url: string | URL,
    svn_url: string | URL,
    homepage: string | URL,
    size: number,
    stargazers_count: number,
    watchers_count: number,
    language: string,
    has_issues: boolean,
    has_projects: boolean,
    has_downloads: boolean,
    has_wiki: boolean,
    has_pages: boolean,
    forks_count: number,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: number,
    license: License,
    allow_forking: true,
    is_template: false,
    topics: string[],
    visibility: string,
    forks: number,
    open_issues: number,
    watchers: number,
    default_branch: string,
    score: number
}

export type Owner = {
    login: string,
    id: number,
    node_id: string,
    avatar_url: string | URL,
    gravatar_id: string | URL,
    url: string | URL,
    html_url: string | URL,
    followers_url: string | URL,
    following_url: string | URL,
    gists_url: string | URL,
    starred_url: string | URL,
    subscriptions_url: string | URL,
    organizations_url: string | URL,
    repos_url: string | URL,
    events_url: string | URL,
    received_events_url: string | URL,
    type: string,
    site_admin: boolean
}

export type License = {
    key: string,
    name: string,
    spdx_id: string,
    url: string | URL,
    node_id: string
}